/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 pot.gltf 
Author: Vision Fountain (https://sketchfab.com/visionfountain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinsese-keepsake-pot-guangdong-china-984c1161626248ee9f765cdffe6c165d
Title: Chinsese Keepsake Pot, Guangdong, China
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pot(props) {
  const { nodes, materials } = useGLTF('/pot.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.11, -0.281, 0.07]} rotation={[1.34, 0.411, -1.796]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_2.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_3.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_4.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_5.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_6.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_7.geometry} material={materials.material0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pot.glb')
