/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vase.glb 
Author: St. Cloud State University Archives (https://sketchfab.com/SCSUArchives)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/chinese-porcelain-crackle-vase-462d30c3e9c54625a41c6bd38b1992fd
Title: Chinese Porcelain Crackle Vase
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Vase(props) {
  const { nodes, materials } = useGLTF('/vase.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.014, 0.222, 1.568]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_2.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_3.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_4.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_5.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_6.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_7.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_8.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_9.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_10.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_11.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_12.geometry} material={materials.material0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vase.glb')
