/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pot-low.glb 
Author: Vision Fountain (https://sketchfab.com/visionfountain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinsese-keepsake-pot-guangdong-china-984c1161626248ee9f765cdffe6c165d
Title: Chinsese Keepsake Pot, Guangdong, China
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pot-low.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} position={[0.084, -0.152, -0.058]} rotation={[-1.801, -0.411, 1.796]} scale={1.564} />
    </group>
  )
}

useGLTF.preload('/pot-low.glb')
