/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vase-low.glb 
Author: St. Cloud State University Archives (https://sketchfab.com/SCSUArchives)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/chinese-porcelain-crackle-vase-462d30c3e9c54625a41c6bd38b1992fd
Title: Chinese Porcelain Crackle Vase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vase-low.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} position={[2.03, 0.054, 9.343]} rotation={[-3.128, -0.222, -1.568]} scale={3.149} />
    </group>
  )
}

useGLTF.preload('/vase-low.glb')
